import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Righteous, Merriweather, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-righteous"
})

const merriweather = Merriweather({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-marriweather"
})

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${righteous.variable} ${merriweather.variable} ${roboto.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
